"""API routes for waveforms."""

import hashlib

from fastapi import APIRouter, Depends, HTTPException, Request, Response
from sqlalchemy.orm import Session
from pathlib import Path
from .. import crud, models, schemas
from ..database import get_db

router = APIRouter()


@router.get("/{track_id}/data")
def get_waveform_data(track_id: int, request: Request, db: Session = Depends(get_db)):
    """Serve the Waveform data v2 blob (ADR 0014) as immutable binary.

    404 until the background generation has produced it; clients retry.
    Waveform data never changes once generated, hence the immutable caching.
    """
    blob = (
        db.query(models.Waveform.data_blob)  # targeted column: never load JSON peaks here
        .filter(models.Waveform.track_id == track_id)
        .scalar()
    )
    if blob is None:
        if not crud.get_track(db, track_id):
            raise HTTPException(status_code=404, detail="Track not found")
        raise HTTPException(
            status_code=404,
            detail="Waveform data not ready yet, retry in a few seconds",
        )

    etag = f'"{hashlib.md5(blob).hexdigest()}"'
    headers = {
        "ETag": etag,
        "Cache-Control": "public, max-age=31536000, immutable",
    }
    if request.headers.get("if-none-match") == etag:
        return Response(status_code=304, headers=headers)
    return Response(content=blob, media_type="application/octet-stream", headers=headers)


@router.get("/{track_id}", response_model=schemas.WaveformResponse)
def get_waveform(track_id: int, db: Session = Depends(get_db)):
    """
    Get waveform data for a track.

    Returns 404 if waveform doesn't exist yet (background worker is generating it).
    Client should retry after a short delay.
    """
    # Check if waveform exists
    waveform = crud.get_waveform(db, track_id)

    if not waveform:
        # Verify track exists
        track = crud.get_track(db, track_id)
        if not track:
            raise HTTPException(status_code=404, detail="Track not found")

        # Waveform is being generated by background worker
        raise HTTPException(
            status_code=404,
            detail="Waveform not ready yet, retry in a few seconds"
        )

    return _format_waveform_response(waveform)


@router.patch("/{track_id}/cue-point")
def update_cue_point(
    track_id: int,
    cue_point_time: float | None,
    db: Session = Depends(get_db)
):
    """Update the CUE point for a track's waveform."""
    waveform = crud.get_waveform(db, track_id)
    if not waveform:
        raise HTTPException(status_code=404, detail="Waveform not found")

    waveform = crud.update_waveform_cue_point(db, track_id, cue_point_time)
    return _format_waveform_response(waveform)


def _format_waveform_response(waveform):
    """Format waveform model for API response."""
    # Lazy: waveform_utils imports librosa at module level (legacy JSON path,
    # deleted in waveform-overhaul issue 04); keep it out of the import chain.
    from ..waveform_utils import json_to_band_peaks

    # Parse multiband data
    low_peaks = json_to_band_peaks(waveform.low_peaks_json)
    mid_peaks = json_to_band_peaks(waveform.mid_peaks_json)
    high_peaks = json_to_band_peaks(waveform.high_peaks_json)

    bands = {
        "low": low_peaks,
        "mid": mid_peaks,
        "high": high_peaks
    }

    # Generate PNG URL if PNG file exists
    png_url = None
    if waveform.png_path:
        # Extract just the filename from the path
        png_filename = Path(waveform.png_path).name
        png_url = f"/waveforms/{png_filename}"

    return {
        "id": waveform.id,
        "track_id": waveform.track_id,
        "data": {
            "sample_rate": waveform.sample_rate,
            "duration": waveform.duration,
            "samples_per_peak": waveform.samples_per_peak,
            "cue_point_time": waveform.cue_point_time,
            "bands": bands
        },
        "png_url": png_url,
        "created_at": waveform.created_at,
        "updated_at": waveform.updated_at
    }
