"""Shipped defaults (setup-guides #293): Murtaza's preferences as defaults.

`backend/shipped_defaults.json` is committed and regenerated by
`scripts/settings/snapshot_defaults.py`. Two sections:

- `settings`: persisted-preference key -> raw string (the `settings` table
  shape). Served by GET /api/settings/defaults; the frontend applies a value
  only when its key is unset (no DB row, no local value).
- `config`: non-path settings-file values (acquisition classification,
  cleanup, download delay). Layered under config.toml: a key present in the
  file wins, a missing key falls back here, then to code defaults.

Inclusion lists live here so the snapshot script and the loader agree.
Excluded by design: audio-routing device IDs, paths, tokens, Export
enablement, session-only keys.
"""

import json
from pathlib import Path
from typing import Any

DEFAULTS_PATH = Path(__file__).parent / "shipped_defaults.json"

# Persisted-preference keys snapshotted verbatim (docs/prds/setup-guides.md).
SETTING_KEYS: tuple[str, ...] = (
    "manadj.grv6JogCalibration",
    "manadj-column-order-v1",
    "manadj-column-widths-v1",
    "manadj-filter-settings",
    "manadj.waveformStyles",
    "manadj-keylock",
    "manadj-quantize",
    "manadj-soft-takeover",
    "manadj-crossfader-assignments",
    "manadj-crossfader-enabled",
    "manadj-follow-flags",
    "manadj-follow-params",
    "manadj-perf-deck-count",
    "manadj-perf-sections",
    "manadj-playlist-filter-enabled",
    "trackListSort",
    "manadj-visualizer-preset",
    "manadj-visualizer-cycle",
    "manadj-visualizer-hud",
    "manadj-visualizer-quality",
    "perf-kbd-hints",
)
SETTING_PREFIXES: tuple[str, ...] = ("manadj-visualizer-params:",)

# Non-path config sections/keys snapshotted from config.toml.
CONFIG_KEYS: dict[str, tuple[str, ...]] = {
    "acquisition": ("download_delay_secs",),
    "acquisition.classification": (
        "clip_max_duration_secs",
        "mix_min_duration_secs",
        "mix_keywords",
        "clip_keywords",
    ),
    "acquisition.cleanup": ("junk_patterns",),
}


def is_shipped_setting(key: str) -> bool:
    return key in SETTING_KEYS or any(key.startswith(p) for p in SETTING_PREFIXES)


def _section(data: dict[str, Any], dotted: str) -> dict[str, Any]:
    node: Any = data
    for part in dotted.split("."):
        node = node.get(part, {}) if isinstance(node, dict) else {}
    return node if isinstance(node, dict) else {}


def select_config(data: dict[str, Any]) -> dict[str, Any]:
    """The CONFIG_KEYS subset of a parsed settings file, nested as in TOML."""
    out: dict[str, Any] = {}
    for dotted, keys in CONFIG_KEYS.items():
        section = _section(data, dotted)
        picked = {k: section[k] for k in keys if k in section}
        if not picked:
            continue
        node = out
        for part in dotted.split("."):
            node = node.setdefault(part, {})
        node.update(picked)
    return out


def load(path: Path = DEFAULTS_PATH) -> dict[str, Any]:
    """Parsed defaults file; empty sections when missing or unreadable."""
    try:
        raw = json.loads(path.read_text())
    except (OSError, ValueError):
        raw = {}
    settings = raw.get("settings") if isinstance(raw, dict) else None
    config = raw.get("config") if isinstance(raw, dict) else None
    return {
        "settings": {
            k: v for k, v in (settings or {}).items()
            if isinstance(v, str) and is_shipped_setting(k)
        },
        "config": select_config(config or {}),
    }


def shipped_settings() -> dict[str, str]:
    return load()["settings"]


def merge_under(data: dict[str, Any], defaults: dict[str, Any]) -> dict[str, Any]:
    """Deep-merge `defaults` beneath `data`: keys present in `data` win."""
    out = dict(defaults)
    for key, value in data.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = merge_under(value, out[key])
        else:
            out[key] = value
    return out


def with_config_defaults(data: dict[str, Any]) -> dict[str, Any]:
    """Settings-file data with shipped non-path values filling unset keys."""
    return merge_under(data, load()["config"])
