#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["jinja2", "markdown", "pyyaml"]
# ///
"""Build the explainer site.

  uv run site/build.py

Inputs:  site/content/ (copy), site/templates/ (layout),
         frontend/src/theme/{tokens,deckColors,routineColor}.ts (design tokens).
Outputs: site/index.html, site/assets/tokens.css, site/assets/logo.png.
"""

from __future__ import annotations

import re
import shutil
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit

import markdown
import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

SITE = Path(__file__).resolve().parent
REPO = SITE.parent
THEME = REPO / "frontend" / "src" / "theme"


# ── Design tokens: derived from tokens.ts, never re-typed (DESIGN.md rule 2) ──


def _ts(name: str) -> str:
    return (THEME / name).read_text(encoding="utf-8")


def _consts(src: str) -> dict[str, str]:
    return dict(re.findall(r"export const (\w+) = '([^']+)';", src))


def _record(src: str, name: str) -> dict[str, str]:
    m = re.search(rf"export const {name}[^=]*= \{{(.*?)\}}", src, re.DOTALL)
    if not m:
        raise SystemExit(f"tokens: record {name} not found")
    return dict(re.findall(r"(\w+):\s*'([^']+)'", m.group(1)))


def build_tokens() -> str:
    tokens = _ts("tokens.ts")
    consts = _consts(tokens) | _consts(_ts("routineColor.ts"))
    lines: list[str] = []
    for var, const in re.findall(r"'(--[\w-]+)':\s*([A-Z][A-Z0-9_]*),", tokens):
        if const in consts:
            lines.append(f"  {var}: {consts[const]};")
    for slot, hexv in _record(tokens, "HOT_CUE_CSS_COLORS").items():
        lines.append(f"  --hc-{slot}: {hexv};")
    for level, hexv in _record(tokens, "ENERGY_COLORS").items():
        lines.append(f"  --energy-{level}: {hexv};")
    for deck, hexv in _record(_ts("deckColors.ts"), "DECK_COLORS").items():
        lines.append(f"  --deck-{deck.lower()}: {hexv};")
    for step, size in _record(tokens, "FONT_SIZES").items():
        lines.append(f"  --font-{step}: {size};")
    steps = re.search(r"SPACE_STEPS = \[([\d,\s]+)\]", tokens)
    if not steps:
        raise SystemExit("tokens: SPACE_STEPS not found")
    for n in steps.group(1).split(","):
        lines.append(f"  --space-{n.strip()}: {n.strip()}px;")
    z = re.search(r"export const Z_TIERS = \{(.*?)\}", tokens, re.DOTALL)
    if not z:
        raise SystemExit("tokens: Z_TIERS not found")
    for tier, n in re.findall(r"(\w+):\s*(\d+)", z.group(1)):
        lines.append(f"  --z-{tier}: {n};")
    rgb = {"accent": consts["ACCENT"], "routine-accent": consts["ROUTINE_ACCENT"]}
    for name, hexv in rgb.items():
        v = int(hexv[1:], 16)
        lines.append(f"  --{name}-rgb: {(v >> 16) & 255}, {(v >> 8) & 255}, {v & 255};")
    required = ("--base", "--crust", "--accent", "--text", "--deck-a", "--font-display", "--space-24", "--z-sticky", "--radius")
    body = "\n".join(lines)
    missing = [r for r in required if f"{r}:" not in body]
    if missing:
        raise SystemExit(f"tokens: missing {missing}")
    return (
        "/* GENERATED by site/build.py from frontend/src/theme/*.ts — do not edit. */\n"
        f":root {{\n{body}\n}}\n"
    )


# ── Content ─────────────────────────────────────────────────────────────────


def _frontmatter(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.DOTALL)
    if not m:
        raise SystemExit(f"{path}: missing frontmatter")
    return yaml.safe_load(m.group(1)), m.group(2)


def _md(text: str) -> str:
    return markdown.markdown(text, extensions=["attr_list"])


def load_content() -> dict:
    content = SITE / "content"
    home, home_body = _frontmatter(content / "home.md")
    home["body_html"] = _md(home_body)

    glossary = yaml.safe_load((content / "glossary.yml").read_text(encoding="utf-8"))
    terms = {t["slug"]: t for t in glossary}

    features = []
    for path in sorted((content / "features").glob("*.md")):
        meta, body = _frontmatter(path)
        for key in ("slug", "kicker", "title", "order"):
            if key not in meta:
                raise SystemExit(f"{path}: frontmatter needs {key!r}")
        unknown = [t for t in meta.get("terms", []) if t not in terms]
        if unknown:
            raise SystemExit(f"{path}: unknown glossary terms {unknown}")
        meta["body_html"] = _md(body)
        meta["term_objs"] = [terms[t] for t in meta.get("terms", [])]
        features.append(meta)
    features.sort(key=lambda f: f["order"])
    slugs = [f["slug"] for f in features]
    if len(set(slugs)) != len(slugs):
        raise SystemExit(f"duplicate feature slugs: {slugs}")
    return {"home": home, "features": features, "glossary": sorted(glossary, key=lambda t: t["term"].lower())}


def validate_page(html: str) -> None:
    """Catch broken anchors and missing media before Pages publishes them."""
    class Links(HTMLParser):
        def __init__(self):
            super().__init__()
            self.ids = []
            self.urls = []

        def handle_starttag(self, tag, attrs):
            for key, value in attrs:
                if key == "id":
                    self.ids.append(value)
                elif key in {"href", "src", "poster"} and value:
                    self.urls.append(value)

    links = Links()
    links.feed(html)
    if len(links.ids) != len(set(links.ids)):
        raise SystemExit("page: duplicate element IDs")
    for raw in links.urls:
        url = urlsplit(raw)
        if url.scheme or url.netloc:
            continue
        if url.path and not (SITE / url.path).is_file():
            raise SystemExit(f"page: missing asset {raw}")
        if not url.path and url.fragment and url.fragment not in links.ids:
            raise SystemExit(f"page: missing anchor {raw}")


def main() -> None:
    (SITE / "assets" / "tokens.css").write_text(build_tokens(), encoding="utf-8")
    shutil.copyfile(REPO / "frontend" / "public" / "logo.png", SITE / "assets" / "logo.png")
    env = Environment(
        loader=FileSystemLoader(SITE / "templates"),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    html = env.get_template("index.html").render(**load_content())
    validate_page(html)
    (SITE / "index.html").write_text(html, encoding="utf-8")
    print(f"built {SITE / 'index.html'}")


if __name__ == "__main__":
    main()
