#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["jinja2", "markdown", "pyyaml"]
# ///
"""Build the explainer site.

  uv run site/build.py

Inputs:  site/content/ (copy), site/templates/ (layout),
         frontend/src/theme/{tokens,deckColors,routineColor}.ts (design tokens).
Outputs: site/index.html, site/help/, site/assets/tokens.css, site/assets/logo.png.
With --app-help: also frontend/public/manual/ (deployable files only).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import tempfile
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

import markdown
import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

SITE = Path(__file__).resolve().parent
REPO = SITE.parent
THEME = REPO / "frontend" / "src" / "theme"


# ── Design tokens: derived from tokens.ts, never re-typed (DESIGN.md rule 2) ──


def _ts(name: str) -> str:
    return (THEME / name).read_text(encoding="utf-8")


def _consts(src: str) -> dict[str, str]:
    return dict(re.findall(r"export const (\w+) = '([^']+)';", src))


def _record(src: str, name: str) -> dict[str, str]:
    m = re.search(rf"export const {name}[^=]*= \{{(.*?)\}}", src, re.DOTALL)
    if not m:
        raise SystemExit(f"tokens: record {name} not found")
    return dict(re.findall(r"(\w+):\s*'([^']+)'", m.group(1)))


def build_tokens() -> str:
    tokens = _ts("tokens.ts")
    consts = _consts(tokens) | _consts(_ts("routineColor.ts"))
    lines: list[str] = []
    for var, const in re.findall(r"'(--[\w-]+)':\s*([A-Z][A-Z0-9_]*),", tokens):
        if const in consts:
            lines.append(f"  {var}: {consts[const]};")
    for slot, hexv in _record(tokens, "HOT_CUE_CSS_COLORS").items():
        lines.append(f"  --hc-{slot}: {hexv};")
    for level, hexv in _record(tokens, "ENERGY_COLORS").items():
        lines.append(f"  --energy-{level}: {hexv};")
    for deck, hexv in _record(_ts("deckColors.ts"), "DECK_COLORS").items():
        lines.append(f"  --deck-{deck.lower()}: {hexv};")
    for step, size in _record(tokens, "FONT_SIZES").items():
        lines.append(f"  --font-{step}: {size};")
    steps = re.search(r"SPACE_STEPS = \[([\d,\s]+)\]", tokens)
    if not steps:
        raise SystemExit("tokens: SPACE_STEPS not found")
    for n in steps.group(1).split(","):
        lines.append(f"  --space-{n.strip()}: {n.strip()}px;")
    z = re.search(r"export const Z_TIERS = \{(.*?)\}", tokens, re.DOTALL)
    if not z:
        raise SystemExit("tokens: Z_TIERS not found")
    for tier, n in re.findall(r"(\w+):\s*(\d+)", z.group(1)):
        lines.append(f"  --z-{tier}: {n};")
    rgb = {"accent": consts["ACCENT"], "routine-accent": consts["ROUTINE_ACCENT"]}
    for name, hexv in rgb.items():
        v = int(hexv[1:], 16)
        lines.append(f"  --{name}-rgb: {(v >> 16) & 255}, {(v >> 8) & 255}, {v & 255};")
    required = ("--base", "--crust", "--accent", "--text", "--deck-a", "--font-display", "--space-24", "--z-sticky", "--radius")
    body = "\n".join(lines)
    missing = [r for r in required if f"{r}:" not in body]
    if missing:
        raise SystemExit(f"tokens: missing {missing}")
    return (
        "/* GENERATED by site/build.py from frontend/src/theme/*.ts — do not edit. */\n"
        f":root {{\n{body}\n}}\n"
    )


# ── Content ─────────────────────────────────────────────────────────────────


def _frontmatter(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.DOTALL)
    if not m:
        raise SystemExit(f"{path}: missing frontmatter")
    return yaml.safe_load(m.group(1)), m.group(2)


def _md(text: str) -> str:
    return markdown.markdown(text, extensions=["extra", "toc"])


def load_content(site: Path = SITE) -> dict:
    content = site / "content"
    home, home_body = _frontmatter(content / "home.md")
    home["body_html"] = _md(home_body)

    glossary = yaml.safe_load((content / "glossary.yml").read_text(encoding="utf-8"))
    terms = {t["slug"]: t for t in glossary}

    features = []
    for path in sorted((content / "features").glob("*.md")):
        meta, body = _frontmatter(path)
        for key in ("slug", "kicker", "title", "order"):
            if key not in meta:
                raise SystemExit(f"{path}: frontmatter needs {key!r}")
        unknown = [t for t in meta.get("terms", []) if t not in terms]
        if unknown:
            raise SystemExit(f"{path}: unknown glossary terms {unknown}")
        meta["body_html"] = _md(body)
        meta["term_objs"] = [terms[t] for t in meta.get("terms", [])]
        features.append(meta)
    features.sort(key=lambda f: f["order"])
    slugs = [f["slug"] for f in features]
    if len(set(slugs)) != len(slugs):
        raise SystemExit(f"duplicate feature slugs: {slugs}")
    return {"home": home, "features": features, "glossary": sorted(glossary, key=lambda t: t["term"].lower())}


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.ids: list[str] = []
        self.urls: list[str] = []

    def handle_starttag(self, tag, attrs):
        for key, value in attrs:
            if key == "id" and value:
                self.ids.append(value)
            elif key in {"href", "src", "poster"} and value:
                self.urls.append(value)


def load_help(site: Path) -> list[dict]:
    articles = []
    for path in sorted((site / "content" / "help").glob("*.md")):
        meta, body = _frontmatter(path)
        for key in ("slug", "title", "summary", "order", "related"):
            if key not in meta:
                raise SystemExit(f"{path}: frontmatter needs {key!r}")
        if not isinstance(meta["slug"], str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", meta["slug"]):
            raise SystemExit(f"{path}: invalid help slug")
        if not isinstance(meta["related"], list) or not all(isinstance(s, str) for s in meta["related"]):
            raise SystemExit(f"{path}: related must be a list of slugs")
        md = markdown.Markdown(extensions=["extra", "toc"])
        meta["body_html"] = md.convert(body)
        meta["toc_html"] = md.toc
        articles.append(meta)
    articles.sort(key=lambda article: (article["order"], article["slug"]))
    by_slug = {a["slug"]: a for a in articles}
    if len(by_slug) != len(articles):
        raise SystemExit("duplicate help slugs")
    for article in articles:
        missing = [slug for slug in article["related"] if slug not in by_slug]
        if missing:
            raise SystemExit(f"help/{article['slug']}: unknown related articles {missing}")
        article["related_articles"] = [by_slug[slug] for slug in article["related"]]
    return articles


def validate_site(root: Path) -> dict[Path, Links]:
    """Resolve links as a browser would, inside a deployable subpath."""
    root = root.resolve()
    pages = {}
    for page in root.rglob("*.html"):
        links = Links()
        links.feed(page.read_text(encoding="utf-8"))
        if len(links.ids) != len(set(links.ids)):
            raise SystemExit(f"{page.relative_to(root)}: duplicate element IDs")
        pages[page] = links
    for page, links in pages.items():
        for raw in links.urls:
            url = urlsplit(raw)
            if url.scheme or url.netloc:
                continue
            if url.path.startswith("/"):
                raise SystemExit(f"{page.relative_to(root)}: root-absolute URL is not subpath safe: {raw}")
            target = (page.parent / unquote(url.path)).resolve() if url.path else page
            if not target.is_relative_to(root):
                raise SystemExit(f"{page.relative_to(root)}: link escapes site: {raw}")
            if target.is_dir():
                target /= "index.html"
            if not target.is_file():
                raise SystemExit(f"{page.relative_to(root)}: missing target/media {raw}")
            if url.fragment and target in pages and unquote(url.fragment) not in pages[target].ids:
                raise SystemExit(f"{page.relative_to(root)}: missing anchor {raw}")
    # Fonts and other CSS assets must also be available offline.
    for css in root.rglob("*.css"):
        for raw in re.findall(r"url\(['\"]?([^)'\"]+)['\"]?\)", css.read_text(encoding="utf-8")):
            url = urlsplit(raw)
            if url.scheme or url.netloc:
                continue
            target = (css.parent / unquote(url.path)).resolve()
            if url.path.startswith("/") or not target.is_relative_to(root) or not target.is_file():
                raise SystemExit(f"{css.relative_to(root)}: missing or nonportable CSS asset {raw}")
    return pages


DEPLOYABLE = ("index.html", "help", "assets", "shots", "media")


def copy_deployable(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for name in DEPLOYABLE:
        src, dest = source / name, destination / name
        if src.is_dir():
            shutil.copytree(src, dest, dirs_exist_ok=True)
        elif src.is_file():
            shutil.copyfile(src, dest)


def build(site: Path = SITE, output: Path = SITE, app_public: Path | None = None) -> None:
    content = load_content(site)
    articles = load_help(site)
    help_slugs = {a["slug"] for a in articles}
    for feature in content["features"]:
        feature["help_url"] = f"help/{feature['slug']}/index.html" if feature["slug"] in help_slugs else None
    env = Environment(
        loader=FileSystemLoader(site / "templates"),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    # Validate fresh output, never stale generated pages from a previous build.
    with tempfile.TemporaryDirectory(prefix="manadj-help-") as tmp:
        stage = Path(tmp).resolve()
        for name in ("assets", "shots", "media"):
            if (site / name).is_dir():
                shutil.copytree(site / name, stage / name)
        (stage / "assets").mkdir(exist_ok=True)
        (stage / "assets" / "tokens.css").write_text(build_tokens(), encoding="utf-8")
        shutil.copyfile(REPO / "frontend" / "public" / "logo.png", stage / "assets" / "logo.png")
        (stage / "index.html").write_text(env.get_template("index.html").render(**content), encoding="utf-8")
        (stage / "help").mkdir()
        template = env.get_template("help.html")
        (stage / "help" / "index.html").write_text(
            template.render(articles=articles, article=None, root="../"), encoding="utf-8")
        for article in articles:
            page = stage / "help" / article["slug"] / "index.html"
            page.parent.mkdir()
            page.write_text(template.render(articles=articles, article=article, root="../../"), encoding="utf-8")
        pages = validate_site(stage)
        manifest = [{"slug": a["slug"], "title": a["title"],
                     "anchors": pages[stage / "help" / a["slug"] / "index.html"].ids}
                    for a in articles]
        (stage / "help" / "manifest.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        # Only the generated help tree is replaced; source assets stay intact.
        if (output / "help").exists():
            shutil.rmtree(output / "help")
        copy_deployable(stage, output)
        if app_public is not None:
            manual = app_public / "manual"
            if manual.is_symlink():
                raise SystemExit(f"refusing symlinked generated directory: {manual}")
            if manual.exists():
                shutil.rmtree(manual)
            copy_deployable(stage, manual)
    print(f"built {output / 'index.html'} and {len(articles)} help articles")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app-help", action="store_true", help="also copy deployable site into frontend/public/manual/")
    args = parser.parse_args()
    build(app_public=REPO / "frontend" / "public" if args.app_help else None)


if __name__ == "__main__":
    main()
