"""pre acquisition baseline

Revision ID: 0001_psrnlqvz
Revises: 
Create Date: 2026-07-02 20:14:05.975964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_psrnlqvz'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_id'), ['id'], unique=False)

    op.create_table('tag_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_categories_id'), ['id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracks_id'), ['id'], unique=False)

    op.create_table('beatgrids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('tempo_changes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beatgrids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beatgrids_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beatgrids_track_id'), ['track_id'], unique=True)

    op.create_table('bpm_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('estimates_json', sa.Text(), nullable=False),
    sa.Column('recommended_bpms_json', sa.Text(), nullable=False),
    sa.Column('recommended_bpm', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bpm_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bpm_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bpm_analyses_track_id'), ['track_id'], unique=True)

    op.create_table('hotcues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotcues', schema=None) as batch_op:
        batch_op.create_index('idx_hotcues_track', ['track_id'], unique=False)
        batch_op.create_index('idx_hotcues_unique', ['track_id', 'slot_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_hotcues_id'), ['id'], unique=False)

    op.create_table('key_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('musical', sa.String(), nullable=False),
    sa.Column('openkey', sa.String(), nullable=True),
    sa.Column('camelot', sa.String(), nullable=True),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scale', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_key_analyses_track_id'), ['track_id'], unique=True)

    op.create_table('playlist_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.create_index('idx_playlist_tracks_playlist', ['playlist_id'], unique=False)
        batch_op.create_index('idx_playlist_tracks_position', ['playlist_id', 'position'], unique=False)
        batch_op.create_index('idx_playlist_tracks_track', ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_tracks_id'), ['id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tag_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tags_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)

    op.create_table('waveforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('samples_per_peak', sa.Integer(), nullable=False),
    sa.Column('low_peaks_json', sa.Text(), nullable=False),
    sa.Column('mid_peaks_json', sa.Text(), nullable=False),
    sa.Column('high_peaks_json', sa.Text(), nullable=False),
    sa.Column('png_path', sa.String(), nullable=True),
    sa.Column('cue_point_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waveforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waveforms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waveforms_track_id'), ['track_id'], unique=True)

    op.create_table('track_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_tags', schema=None) as batch_op:
        batch_op.create_index('idx_track_tags_tag', ['tag_id'], unique=False)
        batch_op.create_index('idx_track_tags_track', ['track_id'], unique=False)
        batch_op.create_index('idx_track_tags_unique', ['track_id', 'tag_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_track_tags_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_tags_id'))
        batch_op.drop_index('idx_track_tags_unique')
        batch_op.drop_index('idx_track_tags_track')
        batch_op.drop_index('idx_track_tags_tag')

    op.drop_table('track_tags')
    with op.batch_alter_table('waveforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waveforms_track_id'))
        batch_op.drop_index(batch_op.f('ix_waveforms_id'))

    op.drop_table('waveforms')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_id'))
        batch_op.drop_index('idx_tags_category')

    op.drop_table('tags')
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_tracks_id'))
        batch_op.drop_index('idx_playlist_tracks_track')
        batch_op.drop_index('idx_playlist_tracks_position')
        batch_op.drop_index('idx_playlist_tracks_playlist')

    op.drop_table('playlist_tracks')
    with op.batch_alter_table('key_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_analyses_track_id'))
        batch_op.drop_index(batch_op.f('ix_key_analyses_id'))

    op.drop_table('key_analyses')
    with op.batch_alter_table('hotcues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotcues_id'))
        batch_op.drop_index('idx_hotcues_unique')
        batch_op.drop_index('idx_hotcues_track')

    op.drop_table('hotcues')
    with op.batch_alter_table('bpm_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bpm_analyses_track_id'))
        batch_op.drop_index(batch_op.f('ix_bpm_analyses_id'))

    op.drop_table('bpm_analyses')
    with op.batch_alter_table('beatgrids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beatgrids_track_id'))
        batch_op.drop_index(batch_op.f('ix_beatgrids_id'))

    op.drop_table('beatgrids')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_filename'))
        batch_op.drop_index(batch_op.f('ix_tracks_file_hash'))

    op.drop_table('tracks')
    with op.batch_alter_table('tag_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_categories_id'))

    op.drop_table('tag_categories')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_id'))

    op.drop_table('playlists')
    # ### end Alembic commands ###
