"""add source items

Revision ID: 0002_ypyywllw
Revises: 0001_psrnlqvz
Create Date: 2026-07-02 20:15:39.775927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_ypyywllw'
down_revision: Union[str, Sequence[str], None] = '0001_psrnlqvz'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('uploader', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('permalink_url', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('liked_at', sa.String(), nullable=True),
    sa.Column('first_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_items_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_items_state'))
        batch_op.drop_index(batch_op.f('ix_source_items_id'))
        batch_op.drop_index(batch_op.f('ix_source_items_external_id'))

    op.drop_table('source_items')
    # ### end Alembic commands ###
