"""add classification

Revision ID: 0003_pkrykxnx
Revises: 0002_ypyywllw
Create Date: 2026-07-02 20:18:56.264200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_pkrykxnx'
down_revision: Union[str, Sequence[str], None] = '0002_ypyywllw'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_column('classification')

    # ### end Alembic commands ###
