"""track duration and source correspondences

Revision ID: 0004_ntoynwsv
Revises: 0003_pkrykxnx
Create Date: 2026-07-02 20:34:03.925836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_ntoynwsv'
down_revision: Union[str, Sequence[str], None] = '0003_pkrykxnx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_correspondences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_item_id', name='uq_correspondence_source_item')
    )
    with op.batch_alter_table('source_correspondences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_correspondences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_correspondences_source_item_id'), ['source_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_correspondences_track_id'), ['track_id'], unique=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_secs', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('duration_secs')

    with op.batch_alter_table('source_correspondences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_correspondences_track_id'))
        batch_op.drop_index(batch_op.f('ix_source_correspondences_source_item_id'))
        batch_op.drop_index(batch_op.f('ix_source_correspondences_id'))

    op.drop_table('source_correspondences')
    # ### end Alembic commands ###
