"""tasks and audio provenance

Revision ID: 0005_qzqmvyum
Revises: 0004_ntoynwsv
Create Date: 2026-07-02 20:52:20.370884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_qzqmvyum'
down_revision: Union[str, Sequence[str], None] = '0004_ntoynwsv'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_type'), ['type'], unique=False)

    op.create_table('audio_provenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_provenances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_provenances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_provenances_track_id'), ['track_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_provenances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_provenances_track_id'))
        batch_op.drop_index(batch_op.f('ix_audio_provenances_id'))

    op.drop_table('audio_provenances')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_state'))
        batch_op.drop_index(batch_op.f('ix_tasks_ref'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    # ### end Alembic commands ###
