"""track file facts

Revision ID: 0007_luvzkmyz
Revises: 0006_mtqsrxsv
Create Date: 2026-07-02 22:35:00.270184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007_luvzkmyz'
down_revision: Union[str, Sequence[str], None] = '0006_mtqsrxsv'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codec', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bitrate_kbps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filesize_bytes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('filesize_bytes')
        batch_op.drop_column('bitrate_kbps')
        batch_op.drop_column('codec')

    # ### end Alembic commands ###
