"""cue to tracks drop legacy waveform columns

Revision ID: 0013_rqwtvtsu
Revises: 0010_rmzqotxl
Create Date: 2026-07-04 18:15:52.718546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013_rqwtvtsu'
down_revision: Union[str, Sequence[str], None] = '0012_rmzqotxl'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Main cue moves to tracks; legacy JSON/PNG waveform columns drop (issue 06).

    The remaining waveform representation is the v2 blob (ADR 0014). Rows
    whose blob is still NULL are re-generated by the task-system sweep at
    the next startup.
    """
    op.add_column("tracks", sa.Column("cue_point_time", sa.Float(), nullable=True))
    op.execute(
        "UPDATE tracks SET cue_point_time = ("
        " SELECT w.cue_point_time FROM waveforms w WHERE w.track_id = tracks.id)"
    )
    with op.batch_alter_table("waveforms") as batch:
        batch.drop_column("low_peaks_json")
        batch.drop_column("mid_peaks_json")
        batch.drop_column("high_peaks_json")
        batch.drop_column("png_path")
        batch.drop_column("cue_point_time")


def downgrade() -> None:
    with op.batch_alter_table("waveforms") as batch:
        batch.add_column(sa.Column("low_peaks_json", sa.Text(), nullable=False, server_default="[]"))
        batch.add_column(sa.Column("mid_peaks_json", sa.Text(), nullable=False, server_default="[]"))
        batch.add_column(sa.Column("high_peaks_json", sa.Text(), nullable=False, server_default="[]"))
        batch.add_column(sa.Column("png_path", sa.String(), nullable=True))
        batch.add_column(sa.Column("cue_point_time", sa.Float(), nullable=True))
    op.execute(
        "UPDATE waveforms SET cue_point_time = ("
        " SELECT t.cue_point_time FROM tracks t WHERE t.id = waveforms.track_id)"
    )
    op.drop_column("tracks", "cue_point_time")
