#!/usr/bin/env python3
"""Generate the frontend key table from backend/key.py — the single Key authority.

`backend/key.py`'s `Key` class is the canonical Key module. This script emits
`frontend/src/utils/keyTable.generated.ts` from `Key.table()` /
`Key.enharmonics()` so the frontend never hand-maintains a second copy of the
24-key mapping. Run at build time (frontend `pregen` / `prebuild` scripts) and
whenever `key.py` changes.

Usage:
    uv run scripts/export/gen_key_table.py           # write the generated file
    uv run scripts/export/gen_key_table.py --check    # verify it is up to date (CI/gate)
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from backend.key import Key  # noqa: E402

OUTPUT = (
    Path(__file__).parent.parent.parent
    / "frontend"
    / "src"
    / "utils"
    / "keyTable.generated.ts"
)


def render() -> str:
    rows = Key.table()
    enharmonics = Key.enharmonics()

    table_lines = []
    for row in rows:
        table_lines.append(
            "  { "
            f"engineId: {row['engine_id']}, "
            f"musical: {json.dumps(row['musical'])}, "
            f"camelot: {json.dumps(row['camelot'])}, "
            f"openkey: {json.dumps(row['openkey'])}, "
            f"mixxxId: {row['mixxx_id']} "
            "},"
        )

    enh_lines = [
        f"  {json.dumps(alt)}: {json.dumps(canonical)},"
        for alt, canonical in enharmonics.items()
    ]

    return (
        "// AUTO-GENERATED by scripts/export/gen_key_table.py from backend/key.py.\n"
        "// DO NOT EDIT. Regenerate with: uv run scripts/export/gen_key_table.py\n"
        "//\n"
        "// backend/key.py's Key class is the single Key authority; this file is\n"
        "// its projection into the frontend. Change key.py, then regenerate.\n"
        "\n"
        "export interface KeyRow {\n"
        "  /** Engine DJ ID (0-23), the canonical internal representation. */\n"
        "  engineId: number;\n"
        "  /** Musical notation, e.g. 'C', 'Am', 'F#m'. */\n"
        "  musical: string;\n"
        "  /** Camelot notation, e.g. '8B', '1A'. */\n"
        "  camelot: string;\n"
        "  /** OpenKey notation, e.g. '1d', '12m' (the preferred display notation). */\n"
        "  openkey: string;\n"
        "  /** Mixxx ID (1-24). */\n"
        "  mixxxId: number;\n"
        "}\n"
        "\n"
        "/** The 24-key table, ordered by Engine DJ ID (0-23). */\n"
        "export const KEY_TABLE: readonly KeyRow[] = [\n"
        + "\n".join(table_lines)
        + "\n];\n"
        "\n"
        "/** Enharmonic/alternative musical spellings → canonical musical name. */\n"
        "export const ENHARMONICS: Readonly<Record<string, string>> = {\n"
        + "\n".join(enh_lines)
        + "\n};\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the generated file is stale (do not write)",
    )
    args = ap.parse_args()

    content = render()

    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(
                f"STALE: {OUTPUT.relative_to(Path.cwd())} is out of date with "
                "backend/key.py. Run: uv run scripts/export/gen_key_table.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"OK: {OUTPUT.name} is up to date with backend/key.py")
        return

    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(Path.cwd())} ({len(Key.table())} keys)")


if __name__ == "__main__":
    main()
