// AUTO-GENERATED by scripts/export/gen_key_table.py from backend/key.py.
// DO NOT EDIT. Regenerate with: uv run scripts/export/gen_key_table.py
//
// backend/key.py's Key class is the single Key authority; this file is
// its projection into the frontend. Change key.py, then regenerate.

export interface KeyRow {
  /** Engine DJ ID (0-23), the canonical internal representation. */
  engineId: number;
  /** Musical notation, e.g. 'C', 'Am', 'F#m'. */
  musical: string;
  /** Camelot notation, e.g. '8B', '1A'. */
  camelot: string;
  /** OpenKey notation, e.g. '1d', '12m' (the preferred display notation). */
  openkey: string;
  /** Mixxx ID (1-24). */
  mixxxId: number;
}

/** The 24-key table, ordered by Engine DJ ID (0-23). */
export const KEY_TABLE: readonly KeyRow[] = [
  { engineId: 0, musical: "C", camelot: "8B", openkey: "1d", mixxxId: 1 },
  { engineId: 1, musical: "Am", camelot: "8A", openkey: "1m", mixxxId: 22 },
  { engineId: 2, musical: "G", camelot: "9B", openkey: "2d", mixxxId: 8 },
  { engineId: 3, musical: "Em", camelot: "9A", openkey: "2m", mixxxId: 17 },
  { engineId: 4, musical: "D", camelot: "10B", openkey: "3d", mixxxId: 3 },
  { engineId: 5, musical: "Bm", camelot: "10A", openkey: "3m", mixxxId: 24 },
  { engineId: 6, musical: "A", camelot: "11B", openkey: "4d", mixxxId: 10 },
  { engineId: 7, musical: "F#m", camelot: "11A", openkey: "4m", mixxxId: 19 },
  { engineId: 8, musical: "E", camelot: "12B", openkey: "5d", mixxxId: 5 },
  { engineId: 9, musical: "C#m", camelot: "12A", openkey: "5m", mixxxId: 14 },
  { engineId: 10, musical: "B", camelot: "1B", openkey: "6d", mixxxId: 12 },
  { engineId: 11, musical: "G#m", camelot: "1A", openkey: "6m", mixxxId: 21 },
  { engineId: 12, musical: "F#", camelot: "2B", openkey: "7d", mixxxId: 7 },
  { engineId: 13, musical: "D#m", camelot: "2A", openkey: "7m", mixxxId: 16 },
  { engineId: 14, musical: "Db", camelot: "3B", openkey: "8d", mixxxId: 2 },
  { engineId: 15, musical: "Bbm", camelot: "3A", openkey: "8m", mixxxId: 23 },
  { engineId: 16, musical: "Ab", camelot: "4B", openkey: "9d", mixxxId: 9 },
  { engineId: 17, musical: "Fm", camelot: "4A", openkey: "9m", mixxxId: 18 },
  { engineId: 18, musical: "Eb", camelot: "5B", openkey: "10d", mixxxId: 4 },
  { engineId: 19, musical: "Cm", camelot: "5A", openkey: "10m", mixxxId: 13 },
  { engineId: 20, musical: "Bb", camelot: "6B", openkey: "11d", mixxxId: 11 },
  { engineId: 21, musical: "Gm", camelot: "6A", openkey: "11m", mixxxId: 20 },
  { engineId: 22, musical: "F", camelot: "7B", openkey: "12d", mixxxId: 6 },
  { engineId: 23, musical: "Dm", camelot: "7A", openkey: "12m", mixxxId: 15 },
];

/** Enharmonic/alternative musical spellings → canonical musical name. */
export const ENHARMONICS: Readonly<Record<string, string>> = {
  "Gb": "F#",
  "Gbm": "F#m",
  "C#": "Db",
  "Dbm": "C#m",
  "Ab": "Ab",
  "Abm": "G#m",
  "Eb": "Eb",
  "Ebm": "D#m",
  "Bb": "Bb",
  "Bbm": "Bbm",
  "C Major": "C",
  "C Minor": "Cm",
  "G Major": "G",
  "G Minor": "Gm",
  "D Major": "D",
  "D Minor": "Dm",
  "A Major": "A",
  "A Minor": "Am",
  "E Major": "E",
  "E Minor": "Em",
  "B Major": "B",
  "B Minor": "Bm",
  "F Major": "F",
  "F Minor": "Fm",
  "Db Major": "Db",
  "Db Minor": "C#m",
  "Ab Major": "Ab",
  "Ab Minor": "G#m",
  "Eb Major": "Eb",
  "Eb Minor": "D#m",
  "Bb Major": "Bb",
  "Bb Minor": "Bbm",
  "F# Major": "F#",
  "F# Minor": "F#m",
  "C# Major": "Db",
  "C# Minor": "C#m",
  "G# Major": "Ab",
  "G# Minor": "G#m",
};
